name: CI

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Use this action for check
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    permissions:
      contents: read # for checkout, and this action requires
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use this action
        id: filter
        uses: ./
        with:
          patterns: |
            **
            "\ # be escaped
            '/%:, # unescaped symbols
            a	b # tab. control characters are escaped
            \n\r\t # treated as a string
          run: |
            echo 'hello'
      - name: Show result
        if: always()
        shell: bash # for windlows
        run: |
          echo '${{ steps.filter.outputs.exists }}' >> "$GITHUB_STEP_SUMMARY"
